### PR TITLE
[PySDK] Flask example for python SDK of WasmEdge

### PR DESCRIPTION
**Pull request by SAtacker**
Please have a look
CC @juntao @apepkuss 
Signed-off-by: Shreyas Atre <shreyasatre16@gmail.com>

### CODE REVIEW

**Comment by apepkuss** [comment]
Hi @SAtacker, could you please list the concrete version of Python3 in README.md? That could be helpful to avoid any version-related issue. Thanks!

**Comment by SAtacker** [comment]
> Hi @SAtacker, could you please list the concrete version of Python3 in README.md? That could be helpful to avoid any version-related issue. Thanks!

Sorry for missing this. It's built for python 3.8 as of now.

**Comment by SAtacker** [comment]
It builds locally so I don't think any specific version of Python3 will create a problem.

**Comment by apepkuss** [comment]
@SAtacker the CI checks failed, please check the issues and fix them, thanks!

**Comment by SAtacker** [comment]
I believe there are no nodejs changes from my end. 
Found the issue listed here https://github.com/WasmEdge/WasmEdge/issues/264

**Pull request merged**
